//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "adjectiv_adverb")]
pub struct Model {
    #[sea_orm(column_type = "Text", nullable)]
    pub word: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub examples: Option<String>,
    pub created_time: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attribute: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub english: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub comparison_forms: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub themes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub meaning: Option<String>,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
