//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "flashcard_reviews")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub review_id: i64,
    pub entry_id: i32,
    #[sea_orm(column_type = "Text")]
    pub result: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub reviewed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vocabulary_entries::Entity",
        from = "Column::EntryId",
        to = "super::vocabulary_entries::Column::EntryId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    VocabularyEntries,
}

impl Related<super::vocabulary_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VocabularyEntries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
