//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub mod prelude;

pub mod adjectiv_adverb;
pub mod flashcard_progress;
pub mod flashcard_reviews;
pub mod vocabulary_entries;
pub mod worter_des_substantivs;
pub mod worter_des_verbs;
