//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::adjectiv_adverb::Entity as AdjectivAdverb;
pub use super::flashcard_progress::Entity as FlashcardProgress;
pub use super::flashcard_reviews::Entity as FlashcardReviews;
pub use super::vocabulary_entries::Entity as VocabularyEntries;
pub use super::worter_des_substantivs::Entity as WorterDesSubstantivs;
pub use super::worter_des_verbs::Entity as WorterDesVerbs;
