-- vocabulary entries --------------------------------------------------------
  CREATE TABLE IF NOT EXISTS vocabulary_entries (
      entry_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      word                  TEXT    NOT NULL,
      part_of_speech        TEXT    NOT NULL,
      english               TEXT,
      meaning               TEXT,
      examples              TEXT,
      themes                TEXT,
      source_table          TEXT    NOT NULL,
      source_created_time   TIMESTAMPTZ,
      extra                 JSONB
  );

  CREATE INDEX IF NOT EXISTS idx_vocabulary_entries_pos
      ON vocabulary_entries (part_of_speech);

  -- progress ------------------------------------------------------------------
  CREATE TABLE IF NOT EXISTS flashcard_progress (
      progress_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      entry_id        INTEGER NOT NULL UNIQUE
          REFERENCES vocabulary_entries(entry_id) ON DELETE CASCADE,
      status          TEXT    NOT NULL,
      times_seen      INTEGER NOT NULL,
      times_mastered  INTEGER NOT NULL,
      last_seen_at    TIMESTAMPTZ,
      created_at      TIMESTAMPTZ NOT NULL,
      updated_at      TIMESTAMPTZ NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_flashcard_progress_status
      ON flashcard_progress (status);

  -- reviews -------------------------------------------------------------------
  CREATE TABLE IF NOT EXISTS flashcard_reviews (
      review_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      entry_id     INTEGER NOT NULL
          REFERENCES vocabulary_entries(entry_id) ON DELETE CASCADE,
      result       TEXT    NOT NULL,
      notes        TEXT,
      reviewed_at  TIMESTAMPTZ NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_entry_id
      ON flashcard_reviews (entry_id);
